### ISSUE TITLE
Outdated csolution.yamld

### ISSUE THREAD

**Issue by francovaro** [alifsemi/alif_vscode-template#5]
Hi,
I tried to compile the code but I think it need small update:
- the name of the `csolution.yaml` file should be named to something like `alif.csolution.yaml` so it can be managed by the CMSIS extension and to avoid error like `error cbuild: invalid csolution file name`
- In the new alif.csolution.yaml I had to update the version requirement for `AlifSemiconductor::Ensemble@1.0.0` to `AlifSemiconductor::Ensemble@1.1.1` as version 1.0.0 is not available anymore.
- In `alif.csolution.yaml` I had to update the version requirement from `ARM::CMSIS@5.6.0` to `ARM::CMSIS@5.9.0`, don't know why but the build system was not able to retrieve the 5.6.0 even if installed.
- I removed version requirment for ARM::CMSIS in the `cproject.yaml`, which I renamed to `alif.cproject.yaml`.

<img width="1290" alt="image" src="https://github.com/alifsemi/alif_vscode-template/assets/9716267/417c7e0a-278d-44a4-b3fa-d5aac6e71ab6">

**Comment by BhupeshKharwa-AlifSemi** [comment]
Version 1.0.0 is still available in our Releases archive and the existing link should work. I tested in my setup. So, not sure why you were seeing problems.


 *  Executing task: cpackget init https://www.keil.com/pack/index.pidx; cpackget add https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack; cpackget add https://github.com/alifsemi/alif_ensemble-cmsis-dfp/releases/download/v1.0.0/AlifSemiconductor.Ensemble.1.0.0.pack; cpackget list; echo 'Pack installation has been completed' 

I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Downloading index.pidx...
I: 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████| (182/182 kB, 2.8 MB/s)         
I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Adding pack "https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack"
E: Pack "https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack" is already installed here: "C:\Alif\VSCode-1.84.2\cmsis-packs\ARM\CMSIS\5.9.0", use the --force-reinstall (-F) flag to force installation
I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Adding pack "https://github.com/alifsemi/alif_ensemble-cmsis-dfp/releases/download/v1.0.0/AlifSemiconductor.Ensemble.1.0.0.pack"
E: Pack "https://github.com/alifsemi/alif_ensemble-cmsis-dfp/releases/download/v1.0.0/AlifSemiconductor.Ensemble.1.0.0.pack" is already installed here: "C:\Alif\VSCode-1.84.2\cmsis-packs\AlifSemiconductor\Ensemble\1.0.0", use the --force-reinstall (-F) flag to force installation
I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Listing installed packs
I: AlifSemiconductor::AzureRTOS@1.0.0
I: AlifSemiconductor::Ensemble@0.5.2
I: AlifSemiconductor::Ensemble@1.0.0
I: AlifSemiconductor::Ensemble@1.0.0-rc4
I: ARM::CMSIS@5.9.0
Pack installation has been completed
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: cpackget init https://www.keil.com/pack/index.pidx; cpackget add https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack; cpackget add https://github.com/alifsemi/alif_ensemble-cmsis-dfp/releases/download/v1.0.0/AlifSemiconductor.Ensemble.1.0.0.pack; cpackget list; echo 'Pack installation has been completed' 

I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Downloading index.pidx...
I: 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████| (182/182 kB, 4.9 MB/s)         
I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Adding pack "https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack"
E: Pack "https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack" is already installed here: "C:\Alif\VSCode-1.84.2\cmsis-packs\ARM\CMSIS\5.9.0", use the --force-reinstall (-F) flag to force installation
I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Adding pack "https://github.com/alifsemi/alif_ensemble-cmsis-dfp/releases/download/v1.0.0/AlifSemiconductor.Ensemble.1.0.0.pack"
I: Downloading AlifSemiconductor.Ensemble.1.0.0.pack...
I: 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████| (9.7/9.7 MB, 50 MB/s)         
I: Extracting files to C:\Alif\VSCode-1.84.2\cmsis-packs\AlifSemiconductor\Ensemble\1.0.0...
I: 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████| (570/570, 355 it/s)         
I: Using pack root: "C:\Alif\VSCode-1.84.2\cmsis-packs"
I: Listing installed packs
I: AlifSemiconductor::Ensemble@1.0.0
I: ARM::CMSIS@5.9.0
Pack installation has been completed
